version: "3.8"
services:
  data:
    image: moa-data:latest
    container_name: moa-data
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
    environment:
      # AWS SDK 인증
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      
      # S3 설정
      - MOA_DATA_S3_BUCKET=${MOA_DATA_S3_BUCKET}
      - MOA_DATA_S3_KEY=${MOA_DATA_S3_KEY}
      
      # 백엔드 URL
      - MOA_BACKEND_URL=${MOA_BACKEND_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
